# Generated by Django 5.1.2 on 2024-10-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alphabet',
            name='female_audio_file',
        ),
        migrations.RemoveField(
            model_name='alphabet',
            name='male_audio_file',
        ),
        migrations.RemoveField(
            model_name='alphabet',
            name='pronunciation_video_file',
        ),
        migrations.RemoveField(
            model_name='word',
            name='animated_video_file',
        ),
        migrations.RemoveField(
            model_name='word',
            name='female_audio_file',
        ),
        migrations.RemoveField(
            model_name='word',
            name='male_audio_file',
        ),
        migrations.RemoveField(
            model_name='word',
            name='pronunciation_video_file',
        ),
        migrations.RemoveField(
            model_name='word',
            name='real_video_file',
        ),
        migrations.AddField(
            model_name='alphabet',
            name='female_audio_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alphabet',
            name='male_audio_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alphabet',
            name='pronunciation_video_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='animated_video_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='female_audio_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='male_audio_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='pronunciation_video_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='real_video_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
