# Generated by Django 5.1.2 on 2024-10-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_alphabet_female_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='english_word',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='hmong_word',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
