# Generated by Django 5.1.2 on 2024-10-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_word_english_word_alter_word_hmong_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='english_word',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='word',
            name='hmong_word',
            field=models.CharField(max_length=255),
        ),
    ]
