# Generated by Django 5.1.2 on 2024-11-11 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_word_image_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='image_filename',
        ),
    ]
