# Generated by Django 5.1.2 on 2024-11-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_word_image_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='image_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
